resources:
  repositories:
    - repository: azure-pipelines # The name used to reference this repository in the checkout step
      type: github
      endpoint: ajschmidt8
      name: ajschmidt8/azure-pipelines
      ref: $(Build.SourceBranchName)

trigger:
  - main

pool:
  vmImage: ubuntu-latest

steps:
  - checkout: azure-pipelines
    clean: true
    # env:
    #   COMMIT_ID: $(Build.SourceVersion)
  - script: echo Hello, world!
    displayName: "Run a one-line script"

  - script: |
      echo Add other tasks to build, test, and deploy your project.
      env
    displayName: "Run a multi-line script"
