# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
  - main

pool:
  vmImage: ubuntu-latest

steps:
  - checkout: git://github.com:ajschmidt8/azure-pipelines@cc629c1
    clean: true
    env:
      COMMIT_ID: $(Build.SourceVersion)
  - script: echo Hello, world!
    displayName: "Run a one-line script"

  - script: |
      echo Add other tasks to build, test, and deploy your project.
      env
    displayName: "Run a multi-line script"
