resources:
  repositories:
    - repository: azure-pipelines
      type: github
      endpoint: ajschmidt8
      name: ajschmidt8/azure-pipelines
      ref: refs/pull/1/head

trigger:
  - main

pool:
  vmImage: ubuntu-latest

steps:
  - checkout: azure-pipelines
    clean: true
  - script: ./script.sh
    displayName: "C++ build"
