jobs:
  - job: style_checks
    steps:
      - script: echo "style checks"
        displayName: "C++ build"
  - job: cpp_build
    steps:
      - script: ./script.sh cpp
        displayName: "C++ build"
  - job: py_build
    dependsOn: cpp_build
    steps:
      - script: ./script.sh py
        displayName: "Python build"
